const quests = [
    { trader: 'mechanic', name: 'Saving the Mole', key: 'saving_the_mole', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Saving_the_Mole' },
    { trader: 'mechanic', name: 'Introduction', key: 'introduction', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Introduction' },
    { trader: 'mechanic', name: 'Signal - Part 1', key: 'signal_part_1', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Signal_-_Part_1' },
    { trader: 'mechanic', name: 'Signal - Part 2', key: 'signal_part_2', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Signal_-_Part_2' },
    { trader: 'mechanic', name: 'Signal - Part 3', key: 'signal_part_3', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Signal_-_Part_3' },
    { trader: 'mechanic', name: 'Signal - Part 4', key: 'signal_part_4', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Signal_-_Part_4' },
    { trader: 'mechanic', name: 'Insider', key: 'insider', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Insider' },
    { trader: 'mechanic', name: 'Scout', key: 'scout', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Scout' },
    { trader: 'mechanic', name: 'Black Swan', key: 'black_swan', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Black_Swan' },
    { trader: 'mechanic', name: 'Forklift Certified', key: 'forklift_certified', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Forklift_Certified' },
    { trader: 'mechanic', name: 'Capacity Check', key: 'capacity_check', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Capacity_Check' },
    { trader: 'mechanic', name: 'Surplus Goods', key: 'surplus_goods', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Surplus_Goods' },
    { trader: 'mechanic', name: 'Back Door', key: 'back_door', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Back_Door' },
    { trader: 'mechanic', name: 'Farming - Part 1', key: 'farming_part_1', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Farming_-_Part_1' },
    { trader: 'mechanic', name: 'Farming - Part 2', key: 'farming_part_2', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Farming_-_Part_2' },
    { trader: 'mechanic', name: 'Farming - Part 3', key: 'farming_part_3', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Farming_-_Part_3' },
    { trader: 'mechanic', name: 'Farming - Part 4', key: 'farming_part_4', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Farming_-_Part_4' },
    { trader: 'mechanic', name: 'Bad Habit', key: 'bad_habit', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Bad_Habit' },
    { trader: 'mechanic', name: 'Psyco Sniper', key: 'psyco_sniper', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Psycho_Sniper' },
    { trader: 'mechanic', name: 'A Shooter Born in Heaven', key: 'a_shooter_born_in_heaven', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/A_Shooter_Born_in_Heaven' },
    { trader: 'mechanic', name: 'Fertilizers', key: 'fertilizers', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Fertilizers' },
    { trader: 'mechanic', name: 'Import', key: 'import', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Import' },
    { trader: 'mechanic', name: 'Chemistry Closet', key: 'chemistry_closet', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Chemistry_Closet' },
    { trader: 'mechanic', name: 'Corporate Secrets', key: 'corporate_secrets', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Corporate_Secrets' },
    { trader: 'mechanic', name: 'Broadcast - Part 1', key: 'broadcast_part_1', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Broadcast_-_Part_1' },
    { trader: 'mechanic', name: 'Energy Crisis', key: 'energy_crisis', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Energy_Crisis' },
    { trader: 'mechanic', name: 'Gunsmith - Part 1', key: 'gunsmith_part_1', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_1' },
    { trader: 'mechanic', name: 'Gunsmith - Part 2', key: 'gunsmith_part_2', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_2' },
    { trader: 'mechanic', name: 'Gunsmith - Part 3', key: 'gunsmith_part_3', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_3' },
    { trader: 'mechanic', name: 'Gunsmith - Part 4', key: 'gunsmith_part_4', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_4' },
    { trader: 'mechanic', name: 'Gunsmith - Part 5', key: 'gunsmith_part_5', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_5' },
    { trader: 'mechanic', name: 'Gunsmith - Part 6', key: 'gunsmith_part_6', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_6' },
    { trader: 'mechanic', name: 'Gunsmith - Part 7', key: 'gunsmith_part_7', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_7' },
    { trader: 'mechanic', name: 'Gunsmith - Part 8', key: 'gunsmith_part_8', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_8' },
    { trader: 'mechanic', name: 'Gunsmith - Part 9', key: 'gunsmith_part_9', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_9' },
    { trader: 'mechanic', name: 'Gunsmith - Part 10', key: 'gunsmith_part_10', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_10' },
    { trader: 'mechanic', name: 'Gunsmith - Part 11', key: 'gunsmith_part_11', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_11' },
    { trader: 'mechanic', name: 'Gunsmith - Part 12', key: 'gunsmith_part_12', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_12' },
    { trader: 'mechanic', name: 'Gunsmith - Part 13', key: 'gunsmith_part_13', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_13' },
    { trader: 'mechanic', name: 'Gunsmith - Part 14', key: 'gunsmith_part_14', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_14' },
    { trader: 'mechanic', name: 'Gunsmith - Part 15', key: 'gunsmith_part_15', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_15' },
    { trader: 'mechanic', name: 'Gunsmith - Part 16', key: 'gunsmith_part_16', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_16' },
    { trader: 'mechanic', name: 'Gunsmith - Part 17', key: 'gunsmith_part_17', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_17' },
    { trader: 'mechanic', name: 'Gunsmith - Part 18', key: 'gunsmith_part_18', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_18' },
    { trader: 'mechanic', name: 'Gunsmith - Part 19', key: 'gunsmith_part_19', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_19' },
    { trader: 'mechanic', name: 'Gunsmith - Part 20', key: 'gunsmith_part_20', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_20' },
    { trader: 'mechanic', name: 'Gunsmith - Part 21', key: 'gunsmith_part_21', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_21' },
    { trader: 'mechanic', name: 'Gunsmith - Part 22', key: 'gunsmith_part_22', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_22' },
    { trader: 'mechanic', name: 'Gunsmith - Part 23', key: 'gunsmith_part_23', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_23' },
    { trader: 'mechanic', name: 'Gunsmith - Part 24', key: 'gunsmith_part_24', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_24' },
    { trader: 'mechanic', name: 'Gunsmith - Part 25', key: 'gunsmith_part_25', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Gunsmith_-_Part_25' },
]

export default quests;