const quests = [
    { trader: 'Prapor', name: 'Shooting Cans', key: 'shooting_cans', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Shooting_Cans' },
    { trader: 'Prapor', name: 'Debut', key: 'debut', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Debut' },
    { trader: 'Prapor', name: 'Luxurious Life', key: 'luxurious_life', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Luxurious_Life' },
    { trader: 'Prapor', name: 'Search Mission', key: 'search_mission', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Search_Mission' },
    { trader: 'Prapor', name: 'Background Check', key: 'background_check', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Background_Check' },
    { trader: 'Prapor', name: 'Shootout Picnic', key: 'shootout_picnic', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Shootout_Picnic' },
    { trader: 'Prapor', name: 'Delivery From the Past', key: 'delivery_from_the_past', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Delivery_From_the_Past' },
    { trader: 'Prapor', name: 'BP Depot', key: 'bp_depot', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/BP_Depot' },
    { trader: 'Prapor', name: 'The Bunker - Part 1', key: 'the_bunker_part_1', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/The_Bunker_-_Part_1' },
    { trader: 'Prapor', name: 'The Bunker - Part 2', key: 'the_bunker_part_2', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/The_Bunker_-_Part_2' },
    { trader: 'Prapor', name: 'Bad Rep Evidence', key: 'bad_rep_evidence', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Bad_Rep_Evidence' },
    { trader: 'Prapor', name: 'Ice Cream Cones', key: 'ice_cream_cones', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Ice_Cream_Cones' },
    { trader: 'Prapor', name: 'No Place for Renegades', key: 'no_place_for_renegades', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/No_Place_for_Renegades' },
    { trader: 'Prapor', name: 'Documents', key: 'documents', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Documents' },
    { trader: 'Prapor', name: 'Postman Pat - Part 1', key: 'postman_pat_part_1', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Postman_Pat_-_Part_1' },
    { trader: 'Prapor', name: 'Possessor', key: 'posessor', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Possessor' },
    { trader: 'Prapor', name: 'Shaking Up the Teller', key: 'shaking_up_the_teller', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Shaking_Up_the_Teller' },
    { trader: 'Prapor', name: 'The Punisher - Part 1', key: 'the_punisher_part_1', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/The_Punisher_-_Part_1' },
    { trader: 'Prapor', name: 'The Punisher - Part 2', key: 'the_punisher_part_2', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/The_Punisher_-_Part_2' },
    { trader: 'Prapor', name: 'The Punisher - Part 3', key: 'the_punisher_part_3', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/The_Punisher_-_Part_3' },
    { trader: 'Prapor', name: 'The Punisher - Part 4', key: 'the_punisher_part_4', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/The_Punisher_-_Part_4' },
    { trader: 'Prapor', name: 'The Punisher - Part 5', key: 'the_punisher_part_5', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/The_Punisher_-_Part_5' },
    { trader: 'Prapor', name: 'The Punisher - Part 6', key: 'the_punisher_part_6', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/The_Punisher_-_Part_6' },
    { trader: 'Prapor', name: 'Anesthesia', key: 'anesthesia', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Anesthesia' },
    { trader: 'Prapor', name: 'Grenadier', key: 'grenadier', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Grenadier' },
    { trader: 'Prapor', name: 'Test Drive - Part 1', key: 'test_drive_part_1', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Test_Drive_-_Part_1' },
    { trader: 'Prapor', name: 'Test Drive - Part 2', key: 'test_drive_part_2', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Test_Drive_-_Part_2' },
    { trader: 'Prapor', name: 'Test Drive - Part 3', key: 'test_drive_part_3', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Test_Drive_-_Part_3' },
    { trader: 'Prapor', name: 'Test Drive - Part 4', key: 'test_drive_part_4', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Test_Drive_-_Part_4' },
    { trader: 'Prapor', name: 'Test Drive - Part 5', key: 'test_drive_part_5', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Test_Drive_-_Part_5' },
    { trader: 'Prapor', name: 'Perfect Mediator', key: 'perfect_mediator', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Perfect_Mediator' },
    { trader: 'Prapor', name: 'Polikhim Hobo', key: 'polikhim_hobo', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Polikhim_Hobo' },
    { trader: 'Prapor', name: 'Regulated Materials', key: 'regulated_materials', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Regulated_Materials' },
    { trader: 'Prapor', name: 'Intimidator', key: 'intimidator', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Intimidator' },
    { trader: 'Prapor', name: 'Easy Job - Part 1', key: 'easy_job_part_1', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Easy_Job_-_Part_1' },
    { trader: 'Prapor', name: 'Easy Job - Part 2', key: 'easy_job_part_2', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Easy_Job_-_Part_2' },
    { trader: 'Prapor', name: 'Reconnaissance', key: 'reconnaissance', wikiLink: 'https://escapefromtarkov.fandom.com/wiki/Reconnaissance' }
]

export default quests;